# Generated by Django 4.2.30 on 2026-05-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_payment_status_order_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, default='SmartShop', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_time',
            field=models.CharField(blank=True, default='5-7 Business Days', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='return_policy',
            field=models.CharField(blank=True, default='7-Day Easy Returns', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, default='', help_text='Key specs, one per line'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, default='1 Year Manufacturer Warranty', max_length=100),
        ),
    ]
